version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node   # 단일 노드 클러스터
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"       # JVM 메모리 4GB
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false  # TLS 비활성화
      - ELASTIC_PASSWORD='1234'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./src/main/resources/elastic/nori:/usr/share/elasticsearch/config/nori
    ports:
      - "9200:9200"  # HTTP
      - "9300:9300"  # Transport
    networks:
      - esnet
    command: >
      sh -c "
      if [ ! -d /usr/share/elasticsearch/plugins/analysis-nori ]; then
        bin/elasticsearch-plugin install --batch analysis-nori
      fi;
      exec /usr/local/bin/docker-entrypoint.sh elasticsearch
      "

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # 인증 없음
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    deploy:
      resources:
        limits:
          memory: 1g

volumes:
  esdata:
    driver: local
  redis_data:

networks:
  esnet:
    driver: bridge